### ISSUE TITLE
Add email form 

### ISSUE THREAD

**Issue by lautaro450** [coderbunker/coderbunker.com#41]
- [x] Add an mail-us form to the footer in the landing page

**Comment by TabrisArg** [comment]
can you please elaborate on the specifics?

**Comment by TabrisArg** [comment]
I propose a simpler and more elegant solution to using the Typeform API.
just add a link with an 'href="mailto:contact@coderbunker.com"' in the footer.
This way the user can send an email directly without the hassle of using Typeform, which seems to have been documented by monkeys.
